name: void_chat_beta
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  keyboard_visibility: any
  font_awesome_flutter: any
  google_fonts: any
  bloc: any
  flutter_bloc: any
  formz: any
  meta: any
  pedantic: any
  shimmer: any
  authentication_repository:
    path: packages/authentication_repository
  firestore_repository:
    path: packages/firestore_repository
  sqflite_repository:
    path: packages/sqflite_repository
  # sqflite:
  path_provider: any
  equatable: any
  hydrated_bloc: any
  get: any
  flutter_form_bloc: any
  simple_animations: any
  flutter_statusbarcolor: any
  flutter_slidable: any
  mockito: any
  cloud_firestore: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.6

flutter:
  uses-material-design: true
  assets:
   - assets/images/
  fonts:
    - family: Iceland
      fonts:
        - asset: fonts/Iceland-Regular.ttf
    - family: Jura
      fonts:
        - asset: fonts/jura/static/Jura-Bold.ttf
        - asset: fonts/jura/static/Jura-Light.ttf
        - asset: fonts/jura/static/Jura-Medium.ttf
        - asset: fonts/jura/static/Jura-Regular.ttf
        - asset: fonts/jura/static/Jura-SemiBold.ttf
