name: void_chat_beta
description: A chat apllication with non Material look and Firebase background.
publish_to: none

version: 1.0.0+2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^9.0.0
  provider: ^5.0.0
  flutter_keyboard_visibility: ^5.0.2
  keyboard_attachable: ^2.0.0
  timeago: ^3.0.2
  bloc: ^7.0.0
  flutter_bloc: ^7.0.1
  hydrated_bloc: ^7.0.1
  formz: ^0.4.0
  meta: ^1.3.0
  shimmer: ^2.0.0
  authentication_repository:
    path: packages/authentication_repository
  firestore_repository:
    path: packages/firestore_repository
  path_provider: ^2.0.2
  equatable: ^2.0.2
  simple_animations: ^3.1.1
  cloud_firestore: ^2.2.0
  intl: null
  flutter_svg: ^0.22.0
  flutter_localizations:
    sdk: flutter
  camera: ^0.8.1+1
  image_picker: ^0.7.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.2
  bloc_test: ^8.0.0
  build_runner: ^2.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Iceland
      fonts:
        - asset: fonts/Iceland-Regular.ttf
    - family: Jura
      fonts:
        - asset: fonts/jura/static/Jura-Bold.ttf
        - asset: fonts/jura/static/Jura-Light.ttf
        - asset: fonts/jura/static/Jura-Medium.ttf
        - asset: fonts/jura/static/Jura-Regular.ttf
        - asset: fonts/jura/static/Jura-SemiBold.ttf
flutter_intl:
  main_locale: en_US
  enabled: true
