name: firestore_repository

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  freezed_annotation:
  flutter:
    sdk: flutter
  cloud_firestore: any
  firebase_storage: ^8.1.0
  async: ^2.5.0
  equatable: ^2.0.0
  firebase_core: ^1.2.0

dev_dependencies:
  build_runner:
  freezed: